<h1 align="center">DATA WRANGLING TRAFFIC CRASHES</h1>

<div style="text-align:center">
<img src="https://i.ibb.co/G3fw6xxV/hit-and-run.jpg" alt="hit-and-run" border="0">
</div>

In this Jupyter Notebook, we'll process and clean the data of car crashes in Chicago city. The dataset, obtained from https://data.cityofchicago.org/Transportation/Traffic-Crashes-Crashes/85ca-t3if/about_data, contains some unstructured and uncategorized fields. Therefore, we have significant data processing ahead for our future analysis and machine learning model training.

## IMPORTING LIBRARIES

We’ll import the necessary libraries for the data wrangling:

In [1]:
import pandas as pd
import numpy as np
import os

## DEFINING VISUALIZATION VALUES

Next, let’s define the values that will affect the visualization options:

In [2]:
import warnings
warnings.filterwarnings('ignore')

See all row and columns in the dataset:

In [3]:
pd.set_option("display.max_columns", None)

Let's read the data obtained from https://data.cityofchicago.org/Transportation/Traffic-Crashes-Crashes/85ca-t3if/about_data:

In [5]:
project_dir = os.path.abspath(os.path.join(os.getcwd(), os.pardir))
data_dir = os.path.join(project_dir, "data", "external")
os.makedirs(data_dir, exist_ok=True)

output_path = os.path.join(data_dir,'Traffic_Crashes_-_Crashes.csv')
df=pd.read_csv(output_path)
df.head(5)

CRASH_RECORD_ID CRASH_DATE_EST_I  \
0  6c1659069e9c6285a650e70d6f9b574ed5f64c12888479...              NaN   
1  5f54a59fcb087b12ae5b1acff96a3caf4f2d37e79f8db4...              NaN   
2  61fcb8c1eb522a6469b460e2134df3d15f82e81fd93e9c...              NaN   
3  004cd14d0303a9163aad69a2d7f341b7da2a8572b2ab33...              NaN   
4  a1d5f0ea90897745365a4cbb06cc60329a120d89753fac...              NaN   

               CRASH_DATE  POSTED_SPEED_LIMIT TRAFFIC_CONTROL_DEVICE  \
0  08/18/2023 12:50:00 PM                  15                  OTHER   
1  07/29/2023 02:45:00 PM                  30         TRAFFIC SIGNAL   
2  08/18/2023 05:58:00 PM                  30            NO CONTROLS   
3  11/26/2019 08:38:00 AM                  25            NO CONTROLS   
4  08/18/2023 10:45:00 AM                  20            NO CONTROLS   

       DEVICE_CONDITION WEATHER_CONDITION LIGHTING_CONDITION  \
0  FUNCTIONING PROPERLY             CLEAR           DAYLIGHT   
1  FUNCTIONING PROPERLY             CLEAR           DAYLIGHT   
2           NO CONTROLS             CLEAR           DAYLIGHT   
3           NO CONTROLS             CLEAR           DAYLIGHT   
4           NO CONTROLS             CLEAR           DAYLIGHT   

       FIRST_CRASH_TYPE                  TRAFFICWAY_TYPE  LANE_CNT  \
0              REAR END                            OTHER       NaN   
1  PARKED MOTOR VEHICLE  DIVIDED - W/MEDIAN (NOT RAISED)       NaN   
2          PEDALCYCLIST                      NOT DIVIDED       NaN   
3            PEDESTRIAN                          ONE-WAY       NaN   
4          FIXED OBJECT                            OTHER       NaN   

            ALIGNMENT ROADWAY_SURFACE_COND ROAD_DEFECT REPORT_TYPE  \
0  STRAIGHT AND LEVEL                  DRY  NO DEFECTS    ON SCENE   
1  STRAIGHT AND LEVEL                  DRY  NO DEFECTS    ON SCENE   
2  STRAIGHT AND LEVEL                  DRY  NO DEFECTS    ON SCENE   
3      CURVE ON GRADE                  DRY  NO DEFECTS    ON SCENE   
4  STRAIGHT AND LEVEL                  DRY  NO DEFECTS    ON SCENE   

                         CRASH_TYPE INTERSECTION_RELATED_I NOT_RIGHT_OF_WAY_I  \
0  INJURY AND / OR TOW DUE TO CRASH                    NaN                NaN   
1            NO INJURY / DRIVE AWAY                    NaN                NaN   
2  INJURY AND / OR TOW DUE TO CRASH                    NaN                NaN   
3  INJURY AND / OR TOW DUE TO CRASH                    NaN                NaN   
4            NO INJURY / DRIVE AWAY                    NaN                NaN   

  HIT_AND_RUN_I         DAMAGE    DATE_POLICE_NOTIFIED  \
0           NaN    OVER $1,500  08/18/2023 12:55:00 PM   
1             Y    OVER $1,500  07/29/2023 02:45:00 PM   
2           NaN  $501 - $1,500  08/18/2023 06:01:00 PM   
3           NaN    OVER $1,500  11/26/2019 08:38:00 AM   
4           NaN    OVER $1,500  08/18/2023 10:48:00 AM   

                  PRIM_CONTRIBUTORY_CAUSE  \
0                   FOLLOWING TOO CLOSELY   
1  FAILING TO REDUCE SPEED TO AVOID CRASH   
2  FAILING TO REDUCE SPEED TO AVOID CRASH   
3                     UNABLE TO DETERMINE   
4                   FOLLOWING TOO CLOSELY   

                              SEC_CONTRIBUTORY_CAUSE  STREET_NO  \
0                  DISTRACTION - FROM INSIDE VEHICLE        700   
1  OPERATING VEHICLE IN ERRATIC, RECKLESS, CARELE...       2101   
2                                UNABLE TO DETERMINE       3422   
3                                     NOT APPLICABLE          5   
4                DRIVING SKILLS/KNOWLEDGE/EXPERIENCE          3   

  STREET_DIRECTION  STREET_NAME  BEAT_OF_OCCURRENCE PHOTOS_TAKEN_I  \
0                W     OHARE ST              1654.0            NaN   
1                S  ASHLAND AVE              1235.0            NaN   
2                N     LONG AVE              1633.0            NaN   
3                W  TERMINAL ST              1655.0              Y   
4                W  TERMINAL ST              1653.0            NaN   

  STATE

In [6]:
df.shape

(913830, 48)

## DATA WRANGLING

Let's see data types and NaN/Null values percentage:

In [7]:
df.dtypes

CRASH_RECORD_ID                   object
CRASH_DATE_EST_I                  object
CRASH_DATE                        object
POSTED_SPEED_LIMIT                 int64
TRAFFIC_CONTROL_DEVICE            object
DEVICE_CONDITION                  object
WEATHER_CONDITION                 object
LIGHTING_CONDITION                object
FIRST_CRASH_TYPE                  object
TRAFFICWAY_TYPE                   object
LANE_CNT                         float64
ALIGNMENT                         object
ROADWAY_SURFACE_COND              object
ROAD_DEFECT                       object
REPORT_TYPE                       object
CRASH_TYPE                        object
INTERSECTION_RELATED_I            object
NOT_RIGHT_OF_WAY_I                object
HIT_AND_RUN_I                     object
DAMAGE                            object
DATE_POLICE_NOTIFIED              object
PRIM_CONTRIBUTORY_CAUSE           object
SEC_CONTRIBUTORY_CAUSE            object
STREET_NO                          int64
STREET_DIRECTION

In [8]:
df.isna().sum()/df.shape[0]*100

CRASH_RECORD_ID                   0.000000
CRASH_DATE_EST_I                 92.629154
CRASH_DATE                        0.000000
POSTED_SPEED_LIMIT                0.000000
TRAFFIC_CONTROL_DEVICE            0.000000
DEVICE_CONDITION                  0.000000
WEATHER_CONDITION                 0.000000
LIGHTING_CONDITION                0.000000
FIRST_CRASH_TYPE                  0.000000
TRAFFICWAY_TYPE                   0.000000
LANE_CNT                         78.221004
ALIGNMENT                         0.000000
ROADWAY_SURFACE_COND              0.000000
ROAD_DEFECT                       0.000000
REPORT_TYPE                       3.138330
CRASH_TYPE                        0.000000
INTERSECTION_RELATED_I           77.010275
NOT_RIGHT_OF_WAY_I               95.453531
HIT_AND_RUN_I                    68.642089
DAMAGE                            0.000000
DATE_POLICE_NOTIFIED              0.000000
PRIM_CONTRIBUTORY_CAUSE           0.000000
SEC_CONTRIBUTORY_CAUSE            0.000000
STREET_NO  

We can drop the columns that don't add value and have several NaN/Null records:

In [9]:
df.drop(columns=['CRASH_RECORD_ID','CRASH_DATE_EST_I', 'LANE_CNT', 'INTERSECTION_RELATED_I', 'NOT_RIGHT_OF_WAY_I', 'STREET_NO',	'STREET_DIRECTION',	'STREET_NAME',
                 'BEAT_OF_OCCURRENCE', 'PHOTOS_TAKEN_I', 'STATEMENTS_TAKEN_I','DOORING_I', 'WORK_ZONE_I', 'WORK_ZONE_TYPE', 'WORKERS_PRESENT_I', 'LOCATION'], inplace=True),

df.shape

(913830, 32)

The following functions will help us to examine column information, replace values and create new date columns:

In [10]:
def print_function(df, column):
  print(df[column].unique())
  print("-"*100)
  print(df[column].value_counts().sort_index())

In [11]:
def unify_other_unknown(df, column):
  df[column].replace(['OTHER', 'UNKNOWN'], 'OTHER/UNKNOWN', inplace=True)

In [12]:
def extract_date(df, new_column, old_column, srt1,str2):
  df[new_column]=df[old_column].str[srt1:str2]
  df[new_column]=pd.to_numeric(df[new_column])
  df[new_column].value_counts().sort_index()

Let's create year column:

In [13]:
extract_date(df, 'CRASH_YEAR', 'CRASH_DATE', 6, 10)

In [14]:
df['CRASH_YEAR'].value_counts().sort_index()

CRASH_YEAR
2013         2
2014         6
2015      9830
2016     44297
2017     83786
2018    118950
2019    117762
2020     92094
2021    108765
2022    108411
2023    110747
2024    112018
2025      7162
Name: count, dtype: int64

2013, 2014, and 2025 have fewer records, so let's remove these years:

In [15]:
years_to_remove = [2013, 2014, 2025]
df = df[~df['CRASH_YEAR'].isin(years_to_remove)]
df['CRASH_YEAR'].unique()

array([2023, 2019, 2022, 2020, 2021, 2018, 2016, 2017, 2015, 2024],
      dtype=int64)

We can drop the "CRASH DATE" column, as it will not be useful for data analysis and ML modeling:

In [16]:
df.drop(columns=['CRASH_DATE'], inplace=True)

Now, we need to examine each column for data categorization and standardization:

### POSTED SPEED LIMIT

In [17]:
print_function(df, 'POSTED_SPEED_LIMIT')

[15 30 25 20 35 10 40 45 55  5 50  0 60  3 65 39  9 22 70 18 99  1 26  2
 24 34  6 14 23 11 32 12 33  7 36 49  8 63 29 38 16 44 62  4 31 46]
----------------------------------------------------------------------------------------------------
POSTED_SPEED_LIMIT
0       7591
1         41
2         31
3        222
4          2
5       4977
6          7
7          6
8          2
9         96
10     21221
11        11
12         4
14         4
15     32317
16         2
18         4
20     37958
22         4
23         3
24        38
25     58187
26        11
29         3
30    667879
31         2
32        20
33        14
34        16
35     59887
36         8
38         2
39        97
40      8685
44         1
45      5988
46         1
49         1
50       281
55       888
60        53
62         1
63         1
65        20
70         7
99        66
Name: count, dtype: int64


We can remove records lower than 5 mph, as speed limits below this value do not exist:

In [18]:
df = df[df['POSTED_SPEED_LIMIT'] >= 5]

print_function(df, 'POSTED_SPEED_LIMIT')

[15 30 25 20 35 10 40 45 55  5 50 60 65 39  9 22 70 18 99 26 24 34  6 14
 23 11 32 12 33  7 36 49  8 63 29 38 16 44 62 31 46]
----------------------------------------------------------------------------------------------------
POSTED_SPEED_LIMIT
5       4977
6          7
7          6
8          2
9         96
10     21221
11        11
12         4
14         4
15     32317
16         2
18         4
20     37958
22         4
23         3
24        38
25     58187
26        11
29         3
30    667879
31         2
32        20
33        14
34        16
35     59887
36         8
38         2
39        97
40      8685
44         1
45      5988
46         1
49         1
50       281
55       888
60        53
62         1
63         1
65        20
70         7
99        66
Name: count, dtype: int64


### TRAFFIC CONTROL DEVICE

In [19]:
print_function(df, 'TRAFFIC_CONTROL_DEVICE')

['OTHER' 'TRAFFIC SIGNAL' 'NO CONTROLS' 'STOP SIGN/FLASHER' 'UNKNOWN'
 'OTHER WARNING SIGN' 'OTHER REG. SIGN' 'YIELD' 'PEDESTRIAN CROSSING SIGN'
 'LANE USE MARKING' 'RAILROAD CROSSING GATE' 'FLASHING CONTROL SIGNAL'
 'SCHOOL ZONE' 'POLICE/FLAGMAN' 'DELINEATORS' 'OTHER RAILROAD CROSSING'
 'RR CROSSING SIGN' 'NO PASSING' 'BICYCLE CROSSING SIGN']
----------------------------------------------------------------------------------------------------
TRAFFIC_CONTROL_DEVICE
BICYCLE CROSSING SIGN           35
DELINEATORS                    351
FLASHING CONTROL SIGNAL        380
LANE USE MARKING              1213
NO CONTROLS                 507123
NO PASSING                      59
OTHER                         6052
OTHER RAILROAD CROSSING        189
OTHER REG. SIGN               1101
OTHER WARNING SIGN             718
PEDESTRIAN CROSSING SIGN       645
POLICE/FLAGMAN                 310
RAILROAD CROSSING GATE         579
RR CROSSING SIGN               199
SCHOOL ZONE                    355
STOP 

Let's unify the other/unknown column categories:

In [20]:
unify_other_unknown(df, 'TRAFFIC_CONTROL_DEVICE')
df['TRAFFIC_CONTROL_DEVICE'].unique()

array(['OTHER/UNKNOWN', 'TRAFFIC SIGNAL', 'NO CONTROLS',
       'STOP SIGN/FLASHER', 'OTHER WARNING SIGN', 'OTHER REG. SIGN',
       'YIELD', 'PEDESTRIAN CROSSING SIGN', 'LANE USE MARKING',
       'RAILROAD CROSSING GATE', 'FLASHING CONTROL SIGNAL', 'SCHOOL ZONE',
       'POLICE/FLAGMAN', 'DELINEATORS', 'OTHER RAILROAD CROSSING',
       'RR CROSSING SIGN', 'NO PASSING', 'BICYCLE CROSSING SIGN'],
      dtype=object)

### DEVICE CONDITION

In [21]:
print_function(df, 'DEVICE_CONDITION')

['FUNCTIONING PROPERLY' 'NO CONTROLS' 'FUNCTIONING IMPROPERLY' 'UNKNOWN'
 'OTHER' 'NOT FUNCTIONING' 'MISSING' 'WORN REFLECTIVE MATERIAL']
----------------------------------------------------------------------------------------------------
DEVICE_CONDITION
FUNCTIONING IMPROPERLY        4085
FUNCTIONING PROPERLY        307995
MISSING                         97
NO CONTROLS                 513221
NOT FUNCTIONING               2553
OTHER                         6788
UNKNOWN                      63745
WORN REFLECTIVE MATERIAL       289
Name: count, dtype: int64


We can unify the other/unknown column categories:

In [22]:
unify_other_unknown(df, 'DEVICE_CONDITION')
df['DEVICE_CONDITION'].unique()

array(['FUNCTIONING PROPERLY', 'NO CONTROLS', 'FUNCTIONING IMPROPERLY',
       'OTHER/UNKNOWN', 'NOT FUNCTIONING', 'MISSING',
       'WORN REFLECTIVE MATERIAL'], dtype=object)

### WEATHER_CONDITION

In [23]:
print_function(df, 'WEATHER_CONDITION')

['CLEAR' 'SNOW' 'UNKNOWN' 'RAIN' 'CLOUDY/OVERCAST' 'FOG/SMOKE/HAZE'
 'BLOWING SNOW' 'FREEZING RAIN/DRIZZLE' 'OTHER' 'SEVERE CROSS WIND GATE'
 'SLEET/HAIL' 'BLOWING SAND, SOIL, DIRT']
----------------------------------------------------------------------------------------------------
WEATHER_CONDITION
BLOWING SAND, SOIL, DIRT         8
BLOWING SNOW                   458
CLEAR                       706259
CLOUDY/OVERCAST              26312
FOG/SMOKE/HAZE                1365
FREEZING RAIN/DRIZZLE         1816
OTHER                         2749
RAIN                         78394
SEVERE CROSS WIND GATE         151
SLEET/HAIL                    1020
SNOW                         28764
UNKNOWN                      51477
Name: count, dtype: int64


Let's unify the other/unknown column categories:

In [24]:
unify_other_unknown(df, 'WEATHER_CONDITION')
df['WEATHER_CONDITION'].unique()

array(['CLEAR', 'SNOW', 'OTHER/UNKNOWN', 'RAIN', 'CLOUDY/OVERCAST',
       'FOG/SMOKE/HAZE', 'BLOWING SNOW', 'FREEZING RAIN/DRIZZLE',
       'SEVERE CROSS WIND GATE', 'SLEET/HAIL', 'BLOWING SAND, SOIL, DIRT'],
      dtype=object)

### LIGHTING CONDITION

In [25]:
print_function(df, 'LIGHTING_CONDITION')

['DAYLIGHT' 'DARKNESS, LIGHTED ROAD' 'DARKNESS' 'UNKNOWN' 'DUSK' 'DAWN']
----------------------------------------------------------------------------------------------------
LIGHTING_CONDITION
DARKNESS                   42442
DARKNESS, LIGHTED ROAD    197897
DAWN                       15027
DAYLIGHT                  575255
DUSK                       25765
UNKNOWN                    42387
Name: count, dtype: int64


We can unify the other/unknown column categories:

In [26]:
unify_other_unknown(df, 'LIGHTING_CONDITION')
df['LIGHTING_CONDITION'].unique()

array(['DAYLIGHT', 'DARKNESS, LIGHTED ROAD', 'DARKNESS', 'OTHER/UNKNOWN',
       'DUSK', 'DAWN'], dtype=object)

### FIRST CRASH TYPE

In [27]:
print_function(df, 'FIRST_CRASH_TYPE' )

['REAR END' 'PARKED MOTOR VEHICLE' 'PEDALCYCLIST' 'PEDESTRIAN'
 'FIXED OBJECT' 'TURNING' 'ANGLE' 'SIDESWIPE SAME DIRECTION'
 'SIDESWIPE OPPOSITE DIRECTION' 'REAR TO SIDE' 'HEAD ON' 'REAR TO FRONT'
 'OTHER OBJECT' 'ANIMAL' 'OTHER NONCOLLISION' 'OVERTURNED' 'REAR TO REAR'
 'TRAIN']
----------------------------------------------------------------------------------------------------
FIRST_CRASH_TYPE
ANGLE                            97866
ANIMAL                             654
FIXED OBJECT                     41631
HEAD ON                           7634
OTHER NONCOLLISION                2729
OTHER OBJECT                      8897
OVERTURNED                         546
PARKED MOTOR VEHICLE            206768
PEDALCYCLIST                     14306
PEDESTRIAN                       21331
REAR END                        199000
REAR TO FRONT                     9292
REAR TO REAR                      1911
REAR TO SIDE                      5537
SIDESWIPE OPPOSITE DIRECTION     12433
SIDESWIPE SAME D

Nothing to do.

### TRAFFICWAY TYPE

In [28]:
print_function(df, 'TRAFFICWAY_TYPE')

['OTHER' 'DIVIDED - W/MEDIAN (NOT RAISED)' 'NOT DIVIDED' 'ONE-WAY'
 'FOUR WAY' 'PARKING LOT' 'DIVIDED - W/MEDIAN BARRIER' 'T-INTERSECTION'
 'UNKNOWN' 'RAMP' 'ALLEY' 'DRIVEWAY' 'UNKNOWN INTERSECTION TYPE'
 'TRAFFIC ROUTE' 'FIVE POINT, OR MORE' 'NOT REPORTED' 'CENTER TURN LANE'
 'L-INTERSECTION' 'Y-INTERSECTION' 'ROUNDABOUT']
----------------------------------------------------------------------------------------------------
TRAFFICWAY_TYPE
ALLEY                               14715
CENTER TURN LANE                     6389
DIVIDED - W/MEDIAN (NOT RAISED)    142142
DIVIDED - W/MEDIAN BARRIER          50920
DRIVEWAY                             2786
FIVE POINT, OR MORE                  1399
FOUR WAY                            63243
L-INTERSECTION                        187
NOT DIVIDED                        388695
NOT REPORTED                          692
ONE-WAY                            113808
OTHER                               23788
PARKING LOT                         58670
RAMP       

Nothing to do.

### ALIGNMENT

In [29]:
print_function(df, 'ALIGNMENT')

['STRAIGHT AND LEVEL' 'CURVE ON GRADE' 'CURVE, LEVEL' 'STRAIGHT ON GRADE'
 'STRAIGHT ON HILLCREST' 'CURVE ON HILLCREST']
----------------------------------------------------------------------------------------------------
ALIGNMENT
CURVE ON GRADE             1302
CURVE ON HILLCREST          383
CURVE, LEVEL               6356
STRAIGHT AND LEVEL       877486
STRAIGHT ON GRADE         11004
STRAIGHT ON HILLCREST      2242
Name: count, dtype: int64


Nothing to do.

### ROADWAY_SURFACE_COND

In [30]:
print_function(df, 'ROADWAY_SURFACE_COND')

['DRY' 'UNKNOWN' 'SNOW OR SLUSH' 'WET' 'OTHER' 'ICE' 'SAND, MUD, DIRT']
----------------------------------------------------------------------------------------------------
ROADWAY_SURFACE_COND
DRY                664322
ICE                  5621
OTHER                2242
SAND, MUD, DIRT       309
SNOW OR SLUSH       28370
UNKNOWN             80024
WET                117885
Name: count, dtype: int64


We can unify the other/unknown column categories:

In [31]:
unify_other_unknown(df, 'ROADWAY_SURFACE_COND')
df['ROADWAY_SURFACE_COND'].unique()

array(['DRY', 'OTHER/UNKNOWN', 'SNOW OR SLUSH', 'WET', 'ICE',
       'SAND, MUD, DIRT'], dtype=object)

### ROAD DEFECT

In [32]:
print_function(df, 'ROAD_DEFECT')

['NO DEFECTS' 'UNKNOWN' 'DEBRIS ON ROADWAY' 'OTHER' 'WORN SURFACE'
 'SHOULDER DEFECT' 'RUT, HOLES']
----------------------------------------------------------------------------------------------------
ROAD_DEFECT
DEBRIS ON ROADWAY       652
NO DEFECTS           715198
OTHER                  4798
RUT, HOLES             6274
SHOULDER DEFECT        1538
UNKNOWN              166600
WORN SURFACE           3713
Name: count, dtype: int64


Let's unify the other/unknown column categories:

In [33]:
unify_other_unknown(df, 'ROAD_DEFECT')
df['ROAD_DEFECT'].unique()

array(['NO DEFECTS', 'OTHER/UNKNOWN', 'DEBRIS ON ROADWAY', 'WORN SURFACE',
       'SHOULDER DEFECT', 'RUT, HOLES'], dtype=object)

### REPORT_TYPE

In [34]:
print_function(df, 'REPORT_TYPE')

['ON SCENE' 'NOT ON SCENE (DESK REPORT)' nan 'AMENDED']
----------------------------------------------------------------------------------------------------
REPORT_TYPE
AMENDED                          230
NOT ON SCENE (DESK REPORT)    487710
ON SCENE                      382558
Name: count, dtype: int64


Let's remove NaN values:

In [35]:
df.dropna(subset=['REPORT_TYPE'], inplace=True)

In [36]:
df.shape

(870498, 32)

### CRASH_TYPE

In [37]:
print_function(df, 'CRASH_TYPE')

['INJURY AND / OR TOW DUE TO CRASH' 'NO INJURY / DRIVE AWAY']
----------------------------------------------------------------------------------------------------
CRASH_TYPE
INJURY AND / OR TOW DUE TO CRASH    231638
NO INJURY / DRIVE AWAY              638860
Name: count, dtype: int64


Nothing to do.

### HIT AND RUN

In [38]:
print_function(df, 'HIT_AND_RUN_I')

[nan 'Y' 'N']
----------------------------------------------------------------------------------------------------
HIT_AND_RUN_I
N     11003
Y    260752
Name: count, dtype: int64


Let's replace NaN values with "DA" (Don't Apply):

In [39]:
df['HIT_AND_RUN_I'].fillna('DA', inplace=True)
print_function(df, 'HIT_AND_RUN_I')

['DA' 'Y' 'N']
----------------------------------------------------------------------------------------------------
HIT_AND_RUN_I
DA    598743
N      11003
Y     260752
Name: count, dtype: int64


### DAMAGE

In [40]:
print_function(df, 'DAMAGE')

['OVER $1,500' '$501 - $1,500' '$500 OR LESS']
----------------------------------------------------------------------------------------------------
DAMAGE
$500 OR LESS      98020
$501 - $1,500    225459
OVER $1,500      547019
Name: count, dtype: int64


### DATE POLICE NOTIFIED

Let's create the month, day and year columns from the 'Police Notified' column:

In [41]:
extract_date(df, 'MONTH_POLICE_NOTIFIED', 'DATE_POLICE_NOTIFIED', 0, 2)
extract_date(df, 'DAY_POLICE_NOTIFIED', 'DATE_POLICE_NOTIFIED', 3, 5)
extract_date(df, 'YEAR_POLICE_NOTIFIED', 'DATE_POLICE_NOTIFIED', 6, 10)

In [42]:
print(df['MONTH_POLICE_NOTIFIED'].value_counts().sort_index())
print('-'*100)
print(df['DAY_POLICE_NOTIFIED'].value_counts().sort_index())
print('-'*100)
print(df['YEAR_POLICE_NOTIFIED'].value_counts().sort_index())

MONTH_POLICE_NOTIFIED
1     63503
2     62620
3     65041
4     63507
5     73984
6     74735
7     75505
8     77681
9     79046
10    83079
11    75435
12    76362
Name: count, dtype: int64
----------------------------------------------------------------------------------------------------
DAY_POLICE_NOTIFIED
1     29522
2     28591
3     28777
4     27862
5     29032
6     28248
7     28104
8     28114
9     28326
10    28623
11    28636
12    29476
13    29158
14    29522
15    29170
16    28950
17    29014
18    28936
19    28582
20    28970
21    28395
22    28580
23    28568
24    27658
25    27562
26    28310
27    28124
28    27687
29    26598
30    26496
31    16907
Name: count, dtype: int64
----------------------------------------------------------------------------------------------------
YEAR_POLICE_NOTIFIED
2015      9316
2016     42606
2017     80339
2018    113699
2019    113223
2020     89222
2021    105114
2022    104031
2023    105927
2024    106897
2025       124
Na

We can drop Data Police Notified column:

In [43]:
df.drop(columns=['DATE_POLICE_NOTIFIED'], inplace=True)

### PRIMARY CONTRIBUTORY CAUSE

In [44]:
print_function(df, 'PRIM_CONTRIBUTORY_CAUSE')

['FOLLOWING TOO CLOSELY' 'FAILING TO REDUCE SPEED TO AVOID CRASH'
 'UNABLE TO DETERMINE' 'IMPROPER BACKING' 'IMPROPER TURNING/NO SIGNAL'
 'NOT APPLICABLE' 'WEATHER' 'IMPROPER OVERTAKING/PASSING'
 'DRIVING SKILLS/KNOWLEDGE/EXPERIENCE' 'IMPROPER LANE USAGE'
 'VISION OBSCURED (SIGNS, TREE LIMBS, BUILDINGS, ETC.)'
 'ROAD ENGINEERING/SURFACE/MARKING DEFECTS'
 'FAILING TO YIELD RIGHT-OF-WAY' 'EQUIPMENT - VEHICLE CONDITION'
 'RELATED TO BUS STOP' 'DISREGARDING OTHER TRAFFIC SIGNS'
 'DRIVING ON WRONG SIDE/WRONG WAY' 'ROAD CONSTRUCTION/MAINTENANCE'
 'DISTRACTION - FROM INSIDE VEHICLE' 'ANIMAL' 'TEXTING'
 'DISREGARDING TRAFFIC SIGNALS' 'DISREGARDING ROAD MARKINGS'
 'CELL PHONE USE OTHER THAN TEXTING' 'DISREGARDING STOP SIGN'
 'OPERATING VEHICLE IN ERRATIC, RECKLESS, CARELESS, NEGLIGENT OR AGGRESSIVE MANNER'
 'EXCEEDING AUTHORIZED SPEED LIMIT' 'DISTRACTION - FROM OUTSIDE VEHICLE'
 'PHYSICAL CONDITION OF DRIVER' 'EXCEEDING SAFE SPEED FOR CONDITIONS'
 'DISREGARDING YIELD SIGN' 'TURNING RIGHT ON RED

Nothing to do.

### SECUNDARY CONTRIBUTORY CAUSE

In [45]:
print_function(df, 'SEC_CONTRIBUTORY_CAUSE')

['DISTRACTION - FROM INSIDE VEHICLE'
 'OPERATING VEHICLE IN ERRATIC, RECKLESS, CARELESS, NEGLIGENT OR AGGRESSIVE MANNER'
 'UNABLE TO DETERMINE' 'NOT APPLICABLE'
 'DRIVING SKILLS/KNOWLEDGE/EXPERIENCE' 'WEATHER'
 'FAILING TO YIELD RIGHT-OF-WAY' 'FAILING TO REDUCE SPEED TO AVOID CRASH'
 'IMPROPER TURNING/NO SIGNAL' 'IMPROPER OVERTAKING/PASSING'
 'FOLLOWING TOO CLOSELY' 'DISREGARDING STOP SIGN'
 'ROAD CONSTRUCTION/MAINTENANCE' 'IMPROPER LANE USAGE'
 'DISTRACTION - FROM OUTSIDE VEHICLE' 'DISREGARDING TRAFFIC SIGNALS'
 'DRIVING ON WRONG SIDE/WRONG WAY' 'EQUIPMENT - VEHICLE CONDITION'
 'IMPROPER BACKING' 'VISION OBSCURED (SIGNS, TREE LIMBS, BUILDINGS, ETC.)'
 'PHYSICAL CONDITION OF DRIVER' 'EXCEEDING SAFE SPEED FOR CONDITIONS'
 'BICYCLE ADVANCING LEGALLY ON RED LIGHT'
 'EXCEEDING AUTHORIZED SPEED LIMIT'
 'DISTRACTION - OTHER ELECTRONIC DEVICE (NAVIGATION DEVICE, DVD PLAYER, ETC.)'
 'UNDER THE INFLUENCE OF ALCOHOL/DRUGS (USE WHEN ARREST IS EFFECTED)'
 'ROAD ENGINEERING/SURFACE/MARKING DEFECTS'

Nothing to do

### NUMBER OF AFFECT UNITS

In [46]:
print_function(df, 'NUM_UNITS')

[ 2  4  1  3  5  6  7  8 12 11  9 18 10 16 14 13 15]
----------------------------------------------------------------------------------------------------
NUM_UNITS
1      48218
2     763637
3      46811
4       8854
5       2066
6        578
7        182
8         85
9         35
10        13
11         6
12         5
13         1
14         1
15         1
16         1
18         4
Name: count, dtype: int64


Nothing to do

### MOST SEVERE INJURY

In [47]:
print_function(df, 'MOST_SEVERE_INJURY')

['NONINCAPACITATING INJURY' 'NO INDICATION OF INJURY' 'FATAL'
 'REPORTED, NOT EVIDENT' 'INCAPACITATING INJURY' nan]
----------------------------------------------------------------------------------------------------
MOST_SEVERE_INJURY
FATAL                          764
INCAPACITATING INJURY        13983
NO INDICATION OF INJURY     749139
NONINCAPACITATING INJURY     67241
REPORTED, NOT EVIDENT        37454
Name: count, dtype: int64


Let's remove NaN values:

In [48]:
df.dropna(subset=['MOST_SEVERE_INJURY'], inplace=True)

In [49]:
df.shape

(868581, 34)

### INJURIES TOTAL

In [50]:
print_function(df, 'INJURIES_TOTAL')

[ 1.  0.  5.  2.  3.  4.  6. 15.  8.  7. 21. 11. 17.  9. 14. 12. 13. 10.
 19. 16.]
----------------------------------------------------------------------------------------------------
INJURIES_TOTAL
0.0     749139
1.0      90197
2.0      19878
3.0       5981
4.0       2111
5.0        763
6.0        289
7.0        116
8.0         46
9.0         21
10.0        11
11.0         9
12.0         4
13.0         3
14.0         1
15.0         6
16.0         1
17.0         1
19.0         1
21.0         3
Name: count, dtype: int64


Nothing to do

In [51]:
print_function(df, 'INJURIES_FATAL')

[0. 1. 2. 3.]
----------------------------------------------------------------------------------------------------
INJURIES_FATAL
0.0    867817
1.0       709
2.0        48
3.0         7
Name: count, dtype: int64


Nothing to do

In [52]:
print_function(df, 'INJURIES_INCAPACITATING')

[ 0.  2.  1.  5.  3.  4.  6. 10.  8.  7.]
----------------------------------------------------------------------------------------------------
INJURIES_INCAPACITATING
0.0     854483
1.0      12434
2.0       1255
3.0        282
4.0         95
5.0         23
6.0          6
7.0          1
8.0          1
10.0         1
Name: count, dtype: int64


Nothing to do

In [53]:
print_function(df, 'INJURIES_NON_INCAPACITATING')

[ 1.  0.  5.  2.  3.  4.  6. 21.  7. 10.  8. 14. 12. 11.  9. 13. 19. 18.
 15. 16.]
----------------------------------------------------------------------------------------------------
INJURIES_NON_INCAPACITATING
0.0     798903
1.0      54816
2.0      10274
3.0       2982
4.0       1016
5.0        353
6.0        143
7.0         50
8.0         16
9.0          7
10.0         5
11.0         4
12.0         4
13.0         1
14.0         1
15.0         1
16.0         1
18.0         1
19.0         1
21.0         2
Name: count, dtype: int64


Nothing to do

In [54]:
print_function(df, 'INJURIES_REPORTED_NOT_EVIDENT')

[ 0.  2.  1.  3.  5.  4. 10.  6.  7.  8.  9. 15.]
----------------------------------------------------------------------------------------------------
INJURIES_REPORTED_NOT_EVIDENT
0.0     826913
1.0      32446
2.0       6670
3.0       1713
4.0        545
5.0        190
6.0         51
7.0         27
8.0         11
9.0          9
10.0         5
15.0         1
Name: count, dtype: int64


Nothing to do

In [55]:
print_function(df, 'INJURIES_NO_INDICATION')

[ 1.  3.  2.  5.  0.  4.  7.  6. 15.  8. 11. 20. 18. 27. 10.  9. 13. 12.
 36. 17. 37. 16. 14. 22. 29. 30. 50. 21. 42. 46. 24. 26. 61. 38. 48. 34.
 31. 43. 19. 45. 25. 40. 49. 23. 41. 28. 33. 35. 32. 39.]
----------------------------------------------------------------------------------------------------
INJURIES_NO_INDICATION
0.0      18349
1.0     265765
2.0     405693
3.0     108946
4.0      40544
5.0      17057
6.0       7103
7.0       2715
8.0       1211
9.0        507
10.0       244
11.0       116
12.0        76
13.0        43
14.0        40
15.0        21
16.0        21
17.0        17
18.0         5
19.0         8
20.0        13
21.0         7
22.0         6
23.0         1
24.0         5
25.0         4
26.0         6
27.0         5
28.0         3
29.0         6
30.0         5
31.0         4
32.0         2
33.0         2
34.0         2
35.0         1
36.0         5
37.0         6
38.0         1
39.0         1
40.0         2
41.0         1
42.0         4
43.0         1
45.0        

Nothing to do

In [56]:
print_function(df, 'INJURIES_UNKNOWN')

[0.]
----------------------------------------------------------------------------------------------------
INJURIES_UNKNOWN
0.0    868581
Name: count, dtype: int64


We can drop this column because doesn't add value:

In [57]:
df.drop(columns=['INJURIES_UNKNOWN'], inplace=True)

In [58]:
df.shape

(868581, 33)

In [59]:
print_function(df, 'CRASH_HOUR')

[12 14 17  8 10 13  0 19 16 11  7 21 15 18  5  6 20  9 22  2  1 23  4  3]
----------------------------------------------------------------------------------------------------
CRASH_HOUR
0     18830
1     15971
2     13617
3     11254
4      9916
5     11826
6     18718
7     36836
8     45939
9     39779
10    39437
11    44079
12    51005
13    52545
14    58049
15    67444
16    66605
17    64933
18    53502
19    39374
20    31883
21    28347
22    26132
23    22560
Name: count, dtype: int64


Nothing to do.

In [60]:
print_function(df, 'CRASH_DAY_OF_WEEK')

[6 7 3 2 1 4 5]
----------------------------------------------------------------------------------------------------
CRASH_DAY_OF_WEEK
1    107948
2    119345
3    123921
4    123269
5    125066
6    140951
7    128081
Name: count, dtype: int64


Nothing to do.

In [61]:
print_function(df, 'CRASH_MONTH')

[ 8  7 11  2  1  9 10 12  5  6  3  4]
----------------------------------------------------------------------------------------------------
CRASH_MONTH
1     63220
2     62582
3     64698
4     63479
5     74109
6     74443
7     75376
8     77483
9     78832
10    82990
11    75065
12    76304
Name: count, dtype: int64


Nothing to do.

In [62]:
print_function(df, 'LATITUDE')
print_function(df, 'LONGITUDE')

[        nan 41.85412026 41.94297574 ... 41.94451595 41.87604366
 41.94508421]
----------------------------------------------------------------------------------------------------
LATITUDE
0.000000     50
41.644670    25
41.644692     5
41.644694     6
41.644694     1
             ..
42.022669     1
42.022720     2
42.022736     1
42.022755     1
42.022780    10
Name: count, Length: 312226, dtype: int64
[         nan -87.66590234 -87.7618835  ... -87.74014511 -87.70045935
 -87.66703451]
----------------------------------------------------------------------------------------------------
LONGITUDE
-87.936193     1
-87.935877     1
-87.934763     3
-87.934510     1
-87.934014     1
              ..
-87.524646     1
-87.524640     1
-87.524589     5
-87.524587    14
 0.000000     50
Name: count, Length: 312226, dtype: int64


In [63]:
df.dropna(subset=['LATITUDE', 'LONGITUDE'], inplace=True)

Let's remove NaN values:

In [64]:
df.shape

(862214, 33)

Let's save the dataset for EDA:

In [65]:
project_dir = os.path.abspath(os.path.join(os.getcwd(), os.pardir))
data_dir = os.path.join(project_dir, "data", "raw")
os.makedirs(data_dir, exist_ok=True)

output_path = os.path.join(data_dir, 'modified_traffic_crashes.csv')
df.to_csv(output_path, index=False)